export function toSnakeCase(str) {
  return str
    .trim()
    .toLowerCase()
    .replace(/\s+/g, '_')
    .replace(/[^\wñáéíóúü]/gu, '')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '');
}

export function applySnakeCaseToFileName(fileName) {
  if (!fileName) {
    return fileName;
  }

  const lastDotIndex = fileName.lastIndexOf('.');
  const nameWithoutExt = lastDotIndex > 0 ? fileName.substring(0, lastDotIndex) : fileName;
  const extension = lastDotIndex > 0 ? fileName.substring(lastDotIndex) : '';
  
  return toSnakeCase(nameWithoutExt) + extension;
}

export function renameFilesForUpload(files, baseName = null) {
  const snakeBaseName = baseName ? toSnakeCase(baseName) : null;
  let photoCounter = 1;
  let videoCounter = 1;

  return files.map(file => {
    const isAutoGeneratedName = !file.fileName || file.fileName.startsWith('photo_') || file.fileName.startsWith('video_');
    
    if (isAutoGeneratedName) {
      if (snakeBaseName) {
        const extension = file.mimeType.startsWith('image/') ? '.jpg' : 
                         file.mimeType.startsWith('video/') ? '.mp4' : '';
        const counter = file.mimeType.startsWith('image/') ? photoCounter++ : videoCounter++;
        
        return {
          ...file,
          fileName: `${snakeBaseName}_${counter}${extension}`,
        };
      }
      return file;
    }

    return {
      ...file,
      fileName: applySnakeCaseToFileName(file.fileName),
    };
  });
}

export function needsUserProvidedName(fileName) {
  if (!fileName) {
    return true;
  }
  
  if (fileName === 'foto.jpg' || fileName === 'video.mp4') {
    return true;
  }
  
  if (fileName.startsWith('photo_') || fileName.startsWith('video_')) {
    return true;
  }
  
  return false;
}
